-- Supabase / PostgreSQL schema for Quiz Diário de Ciência

-- Drop tables if they exist (to recreate with correct schema)
drop table if exists answers cascade;
drop table if exists profiles cascade;
drop table if exists questions cascade;

-- Table: profiles
create table profiles (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text,
  points integer not null default 0,
  last_answer_date date,
  created_at timestamp with time zone default now()
);

-- Table: questions
create table questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct char(1) not null check (correct in ('A','B','C','D')),
  created_at timestamp with time zone default now()
);

-- Table: answers (history)
create table answers (
  id bigint generated by default as identity primary key,
  profile_id bigint references profiles(id) on delete cascade,
  question_id bigint references questions(id) on delete cascade,
  answered_at timestamp with time zone default now(),
  correct boolean not null
);

-- Example inserts
insert into questions (question_text, option_a, option_b, option_c, option_d, correct)
values
('Qual é a unidade básica da vida?','Átomo','Célula','Molécula','Órgão','B'),
('Qual planeta é conhecido como Planeta Vermelho?','Vênus','Saturno','Marte','Júpiter','C'),
('Qual destes é uma fonte de energia renovável?','Petróleo','Carvão','Vento','Gás Natural','C'),
('Qual gás é mais abundante na atmosfera da Terra?','Oxigênio','Nitrogênio','Dióxido de Carbono','Hélio','B'),
('Qual é a velocidade aproximada da luz no vácuo?','300.000 km/s','30.000 km/s','300 km/s','3.000 km/s','A'),
('Qual é o principal órgão do sistema circulatório?','Pulmões','Fígado','Coração','Rim','C')
on conflict do nothing;

-- Enable RLS
alter table profiles enable row level security;
alter table questions enable row level security;
alter table answers enable row level security;

-- Policies for public access (since using anon key)
create policy "Allow all operations on profiles" on profiles for all using (true);
create policy "Allow all operations on questions" on questions for all using (true);
create policy "Allow all operations on answers" on answers for all using (true);
